const subjects=[
{id:"maths",name:"Mathematics",icon:"∑",tint:"#e7e2ff",desc:"Number, algebra, geometry, statistics & probability",topics:["Number & calculation","Algebraic manipulation","Equations & inequalities","Graphs & sequences","Ratio, proportion & rates","Geometry & measures","Probability","Statistics"],links:[["AQA specification","https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300"]]},
{id:"english",name:"English Language",icon:"Aa",tint:"#ffe8d1",desc:"Reading, analysis, creative & transactional writing",topics:["Paper 1: Explorations in creative reading","Paper 1: Creative writing","Paper 2: Writers' viewpoints","Paper 2: Non-fiction writing","Language & structure","Evaluation & comparison"],links:[["AQA specification","https://www.aqa.org.uk/subjects/english/gcse/english-language-8700"]]},
{id:"literature",name:"English Literature",icon:"▤",tint:"#ffe1e7",desc:"Shakespeare, 19th-century, modern texts & poetry",topics:["Shakespeare: plot & characters","Shakespeare: themes & methods","19th-century novel","Modern text / play","Power & conflict poetry","Unseen poetry"],links:[["AQA specification","https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702"]]},
{id:"science",name:"Combined Science",icon:"⚗",tint:"#dff5eb",desc:"Biology, chemistry and physics core knowledge",topics:["Cell biology","Organisation","Infection & response","Bioenergetics","Atomic structure","Bonding & quantitative chemistry","Energy","Electricity"],links:[["AQA GCSE Science","https://www.aqa.org.uk/subjects/science/gcse"]]},
{id:"geography",name:"Geography",icon:"⌁",tint:"#dff0ff",desc:"Living world, urban issues, hazards & fieldwork",topics:["Natural hazards","The living world","Physical landscapes in the UK","Urban issues & challenges","Economic world","Resource management","Geographical skills & fieldwork"],links:[["AQA Geography","https://www.aqa.org.uk/subjects/geography/gcse/geography-8035"]]},
{id:"computer",name:"Computer Science",icon:"</>",tint:"#e7edff",desc:"Algorithms, programming, data, systems & networks",topics:["Algorithms","Programming fundamentals","Data representation","Computer systems","Networks","Cyber security","Databases & SQL","Ethical, legal & environmental impacts"],links:[["AQA specification","https://www.aqa.org.uk/subjects/computer-science-and-it/gcse/computer-science-8525"]]},
{id:"french",name:"French",icon:"FR",tint:"#ffe4ec",desc:"Vocabulary, grammar, listening, speaking, reading & writing",topics:["Identity & relationships","Healthy living","School & future plans","Local area & holidays","International & global issues","Present / past / future tenses","Speaking role-play & photo card"],links:[["AQA specification","https://www.aqa.org.uk/subjects/languages/gcse/french-8652"]]}
];

const qs=[
["Mathematics","What is the gradient of y = 3x + 2?","3",["2","3","-3","5"]],
["Computer Science","Which data structure uses FIFO?","Queue",["Stack","Queue","Tree","Array"]],
["Science","What is the chemical symbol for sodium?","Na",["So","S","Na","N"]],
["Geography","What is urbanisation?","The growth in the proportion of people living in urban areas",["A fall in city populations","The growth in the proportion of people living in urban areas","Migration from cities to villages","Building a new motorway"]],
["French","Which means 'I went'?","Je suis allé(e)",["Je vais","J'allais","Je suis allé(e)","J'irai"]],
["English Language","Which method focuses on a writer's choice of words?","Language",["Language","Structure","Form","Context"]]];

const state=JSON.parse(localStorage.getItem("year10hub")||'{"done":[],"best":0}');
let currentQuiz=0, quizScore=0, quizAnswered=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem("year10hub",JSON.stringify(state));renderStats()}
function renderStats(){let total=subjects.reduce((a,s)=>a+s.topics.length,0);let done=state.done.length;$("#topicsDone").textContent=`${done} / ${total}`;$("#progressBar").style.width=`${Math.round(done/total*100)}%`;$("#quizScore").textContent=`${state.best}%`;$("#streak").textContent=`${done?Math.min(done,7):0} days 🔥`}
function card(s){let done=s.topics.filter(t=>state.done.includes(s.id+"|"+t)).length;return `<article class="subject-card" style="--tint:${s.tint}" data-subject="${s.id}"><div class="subject-icon">${s.icon}</div><h3>${s.name}</h3><p>${s.desc}</p><div class="mini-progress"><i style="width:${done/s.topics.length*100}%"></i></div><small>${done}/${s.topics.length} topics complete</small></article>`}
function renderSubjects(filter=""){let arr=subjects.filter(s=>(s.name+" "+s.desc).toLowerCase().includes(filter.toLowerCase()));$("#allSubjects").innerHTML=arr.map(card).join("");$$("[data-subject]").forEach(x=>x.onclick=()=>openSubject(x.dataset.subject))}
function openSubject(id){let s=subjects.find(x=>x.id===id);$("#detailContent").innerHTML=`<div class="detail-head"><div class="subject-icon" style="--tint:${s.tint}">${s.icon}</div><div><p class="eyebrow">AQA · YEAR 10</p><h1>${s.name}</h1><p>${s.desc}</p></div></div><div class="topic-list">${s.topics.map((t,i)=>{let key=s.id+"|"+t, checked=state.done.includes(key);return `<div class="topic"><input type="checkbox" data-topic="${key}" ${checked?"checked":""}><div><strong>${t}</strong><small>Core revision target · Topic ${i+1}</small></div><div class="resource-links">${s.links.map(l=>`<a href="${l[1]}" target="_blank" rel="noopener">${l[0]} ↗</a>`).join("")}</div></div>`}).join("")}</div>`;$$("[data-topic]").forEach(c=>c.onchange=()=>{let k=c.dataset.topic;if(c.checked&&!state.done.includes(k))state.done.push(k);if(!c.checked)state.done=state.done.filter(x=>x!==k);save()});show("subjectDetail")}
function show(id){$$(".view").forEach(v=>v.classList.remove("active"));$("#"+id).classList.add("active");$$(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===id))}
function renderPlanner(){let days=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];$("#plannerList").innerHTML=days.map(d=>`<div class="planner-row"><strong>${d}</strong><select><option>Maths</option>${subjects.slice(1).map(s=>`<option>${s.name}</option>`).join("")}</select><span>30 min</span></div>`).join("")}
function renderQuiz(){let q=qs[currentQuiz];$("#quizBox").innerHTML=`<div class="quiz-meta"><span>${q[0]}</span><span>Question ${currentQuiz+1}/${qs.length}</span></div><div class="quiz-q">${q[1]}</div><div class="answers">${q[3].map(a=>`<button class="answer">${a}</button>`).join("")}</div><button class="primary next" id="next" style="display:none">Next →</button>`;$$(".answer").forEach(b=>b.onclick=()=>{if(quizAnswered)return;quizAnswered=true;let ok=b.textContent===q[2];b.classList.add(ok?"correct":"wrong");if(ok)quizScore++;if(!ok)$$(".answer").find(x=>x.textContent===q[2]).classList.add("correct");$("#next").style.display="inline-block";});$("#next").onclick=()=>{currentQuiz++;quizAnswered=false;if(currentQuiz>=qs.length){state.best=Math.max(state.best,Math.round(quizScore/qs.length*100));save();currentQuiz=0;quizScore=0;$("#quizBox").innerHTML=`<h2>Quiz complete 🎯</h2><p>Your score was saved. Best score: <strong>${state.best}%</strong>.</p><button class="primary" onclick="renderQuiz()">Try again</button>`}else renderQuiz()}}
$("#nav").onclick=e=>{let b=e.target.closest("[data-view]");if(b){show(b.dataset.view);if(b.dataset.view==="subjects")renderSubjects();if(b.dataset.view==="planner")renderPlanner();if(b.dataset.view==="quiz")renderQuiz();}}
$$("[data-view]").forEach(b=>b.addEventListener("click",()=>{let v=b.dataset.view;if(v==="subjects")renderSubjects()}));
$("#backSubjects").onclick=()=>{renderSubjects();show("subjects")};
$("#search").oninput=e=>{let q=e.target.value.trim();if(q){show("subjects");renderSubjects(q)}};
$("#darkBtn").onclick=()=>document.body.classList.toggle("dark");
$("#resetBtn").onclick=()=>{if(confirm("Reset all saved progress?")){state.done=[];state.best=0;save();renderSubjects();}};
$("#mobileMenu").onclick=()=>$(".sidebar").classList.toggle("open");
$("#dashboardSubjects").innerHTML=subjects.slice(0,6).map(card).join("");$$("[data-subject]").forEach(x=>x.onclick=()=>openSubject(x.dataset.subject));
renderStats();renderSubjects();
